plugins:
  collude_enabled:
    default: true
    client: true
  collude_debounce:
    default: 500
    min: 100
    client: true
  collude_server_debounce:
    default: 10
    min: 2
  collude_min_trust_level:
    default: 2
    min: 0
    max: 4
